book/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.BookListView.as_view(), name="book_list"),
    path("detail/<slug:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("search/", views.book_search, name="book_search"),

    path("author/detail/<slug:pk>/", views.AuthorDetailView.as_view(), name="author_detail"),
    path("author/", views.AuthorListView.as_view(), name="author_list"),

    path("genre/detail/<slug:pk>/", views.GenreDetailView.as_view(), name="genre_detail"),
    path("genre/", views.GenreListView.as_view(), name="genre_list"),
]

cart/urls.py
# cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/<int:quantity>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

library/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from library import settings

urlpatterns = [
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('books/', include('book.urls')),
    path('cart/', include('cart.urls', namespace='cart')),

    path('order/', include('orders.urls')),

    path('admin/', admin.site.urls),
]

book/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Author(models.Model):
    name = models.TextField()
    description = models.TextField()
    books = models.ManyToManyField('Book', blank=True)
    birthday = models.DateField(null=True, blank=True)

    class Meta:
        db_table = "author"
    
    def __str__(self):
        return self.name
    
        
class Genre(models.Model):
    name = models.TextField()
    description = models.TextField()
    books = models.ManyToManyField('Book', blank=True)

    class Meta:
        db_table = "genre"
    
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING)
    uri = models.TextField()
    publication_date = models.DateField(default=timezone.now)
    authors = models.ManyToManyField(Author)
    genres = models.ManyToManyField(Genre, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.title


class Review(models.Model):
    book = models.ForeignKey(Book, models.DO_NOTHING)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING)
    content = models.TextField(blank=True, null=True)
    rating = models.SmallIntegerField()

    class Meta:
        db_table = 'review'
    

book/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import TemplateView, ListView, DetailView

from book.models import Book, Author, Genre


class BookListView(ListView):
    model = Book
    template_name = 'book_list.html'
    context_object_name = 'books'


class BookDetailView(DetailView):
    model = Book
    template_name = 'book_detail.html'
    context_object_name = 'book'


class AuthorListView(ListView):
    model = Author
    template_name = 'author_list.html'
    context_object_name = 'authors'


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author_detail.html'
    context_object_name = 'author'


class GenreListView(ListView):
    model = Genre
    template_name = 'genre_list.html'
    context_object_name = 'genres'


class GenreDetailView(DetailView):
    model = Genre
    template_name = 'genre_detail.html'
    context_object_name = 'genre'


def book_search(request):
    # Получаем все жанры для выпадающего списка
    all_genres = Genre.objects.all()

    # Получаем параметры поиска
    query = request.GET.get('q', '')
    author_query = request.GET.get('author', '')
    genre_name = request.GET.get('genre', '')

    # Начинаем с полного набора книг
    books = Book.objects.all()

    # Применяем фильтры
    if query:
        books = books.filter(title__icontains=query)
    if author_query:
        books = books.filter(authors__name__icontains=author_query)
    if genre_name:
        books = books.filter(genres__name__icontains=genre_name)

    context = {
        'books': books,
        'all_genres': all_genres,
        'request': request,
        'is_not_found': books.count() == 0,
    }
    return render(request, 'book_search_result.html', context)

book/templates/author_detail.html
{% extends "home.html" %}
{% block content %}
    <h1>{{ author.name }}</h1>
    <p><strong>Birth Date:</strong> {{ author.birthday|date:"d-m-Y" }}</p>
    <h2>Books by {{ author.name }}</h2>
    <ul>
        {% for book in author.book_set.all %}
            <li><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a> ({{ book.publication_date|date:"d-m-Y" }})
            </li>
        {% empty %}
            <li>No books by this author.</li>
        {% endfor %}
    </ul>
{% endblock %}

book/templates/author_list.html
{% extends "home.html" %}
{% block content %}
    <h1>Authors</h1>
    <ul>
        {% for author in authors %}
            <li><a href="{% url 'author_detail' author.pk %}">{{ author.name }}</a>
                (Born: {{ author.birthday|date:"d-m-Y" }})
            </li>
        {% empty %}
            <li>No authors available.</li>
        {% endfor %}
    </ul>
{% endblock %}

book/templates/book_detail.html
{% extends "home.html" %}
{% block content %}
    <h1>{{ book.title }}</h1>
    <p><strong>Authors:</strong></p>
    {% for author in book.authors.all %}
        <li><a href="{% url 'author_detail' author.pk %}">{{ author.name }}</a></li>
    {% empty %}
        No authors
    {% endfor %}

    <p><strong>Genres:</strong></p>
    {% for genre in book.genres.all %}
        <li><a href="{% url 'genre_detail' genre.pk %}">{{ genre.name }}</a></li>
    {% empty %}
        No genres
    {% endfor %}
    <p><strong>Publication Date:</strong> {{ book.publication_date|date:"d-m-Y" }}</p>
{% endblock %}

book/templates/book_list.html
{% extends "home.html" %}
{% block content %}
    <h1>Books</h1>
    <form method="get" action="{% url 'book_search' %}" class="book-search-form">
        <div class="search-fields">
            <input type="text"
                   name="q"
                   placeholder="Название книги"
                   value="{{ request.GET.q }}"
                   class="search-input">

            <input type="text"
                   name="author"
                   placeholder="Автор"
                   value="{{ request.GET.author }}"
                   class="search-input">

            <input type="text"
                   name="genre"
                   placeholder="Жанр"
                   value="{{ request.GET.genre }}"
                   class="search-input">
        </div>
        <button type="submit" class="search-button">Найти</button>
    </form>
    <ul>
        {% for book in books %}
            <li><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a> by {{ book.authors.0 }}
                ({{ book.publication_date|date:"d-m-Y" }})
            </li>
            <form action="{% url 'cart:cart_add' book.pk 1 %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину">
            </form>
        {% empty %}
            <li>No books available.</li>
        {% endfor %}
    </ul>
{% endblock %}

book/templates/book_search_result.html
{% extends "home.html" %}

{% block content %}
    <h2>Результаты поиска</h2>

    {% if books %}
        <ul class="book-list">
            {% for book in books %}
                <li>
                    <a href="{% url 'book_detail' book.id %}">
                        {{ book.title }}
                    </a>
                    <p>Авторы:
                        {% for author in book.authors.all %}
                            {{ author.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <p>Жанры:
                        {% for genre in book.genres.all %}
                            {{ genre.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Книги не найдены</p>
    {% endif %}
{% endblock %}

book/templates/genre_detail.html
{% extends "home.html" %}
{% block content %}
    <h1>{{ genre.name }}</h1>
    <h2>Books in {{ genre.name }}</h2>
    <ul>
        {% for book in genre.book_set.all %}
            <li><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a> by {{ book.author.name }}
                ({{ book.publication_date|date:"d-m-Y" }})
            </li>
        {% empty %}
            <li>No books in this genre.</li>
        {% endfor %}
    </ul>
{% endblock %}

book/templates/genre_list.html
{% extends "home.html" %}
{% block content %}
    <h1>Genres</h1>
    <ul>
        {% for genre in genres %}
            <li><a href="{% url 'genre_detail' genre.pk %}">{{ genre.name }}</a></li>
        {% empty %}
            <li>No genres available.</li>
        {% endfor %}
    </ul>
{% endblock %}