book/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.BookListView.as_view(), name="book_list"),
    path("detail/<slug:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("search/", views.book_search, name="book_search"),

    path("author/detail/<slug:pk>/", views.AuthorDetailView.as_view(), name="author_detail"),
    path("author/", views.AuthorListView.as_view(), name="author_list"),

    path("genre/detail/<slug:pk>/", views.GenreDetailView.as_view(), name="genre_detail"),
    path("genre/", views.GenreListView.as_view(), name="genre_list"),
]

cart/urls.py
# cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/<int:quantity>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

library/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from library import settings

urlpatterns = [
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('books/', include('book.urls')),
    path('cart/', include('cart.urls', namespace='cart')),

    path('order/', include('orders.urls')),

    path('admin/', admin.site.urls),
]

cart/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.

# cart/cart.py
from decimal import Decimal
from django.conf import settings
from book.models import Book

class Cart:
    def __init__(self, request):
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)
        if not cart:
            cart = self.session[settings.CART_SESSION_ID] = {}
        self.cart = cart

    def add(self, product, quantity=1, update_quantity=False):
        product_id = str(product.id)
        if product_id not in self.cart:
            self.cart[product_id] = {
                'quantity': 0,
                'price': str(product.price)
            }
        if update_quantity:
            self.cart[product_id]['quantity'] = quantity
        else:
            self.cart[product_id]['quantity'] += quantity
        self.save()

    def save(self):
        self.session.modified = True

    def remove(self, product):
        product_id = str(product.id)
        del self.cart[product_id]

    def __iter__(self):
        product_ids = self.cart.keys()
        products = Book.objects.filter(id__in=product_ids)
        cart = self.cart.copy()

        for product in products:
            cart[str(product.id)]['product'] = product

        for key, item in cart.items():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def __len__(self):
        return sum(item['quantity'] for item in self.cart.values())

    def books(self):
        product_ids = self.cart.keys()

        books = {}
        for id in product_ids:
            books[Book.objects.get(id=id)] = self.cart[id]['quantity']

        return books

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

    def clear(self):
        del self.session[settings.CART_SESSION_ID]
        self.save()

cart/views.py
from django import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Cart
from book.models import Book


def cart(request):
    return {'cart': Cart(request)}


@require_POST
def cart_add(request, product_id, quantity):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)

    cart.add(
        product=product,
        quantity=quantity,
        update_quantity=False,
    )

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart_detail.html', {'cart': cart})


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        min_value=1,
        required=True,
        initial=1,
        widget=forms.HiddenInput(),
    )
    update = forms.BooleanField(
        required=False, initial=False,
        widget=forms.HiddenInput
    )

cart/templates/cart_detail.html
<!-- templates/cart/detail.html -->
{% extends "home.html" %}

{% block title %}Корзина{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>

    {% with total_items=cart|length %}
        {% if total_items > 0 %}
            <table class="cart-table">
                <thead>
                <tr>
                    <th>Товар</th>
                    <th>Количество</th>
                    <th>Цена за шт.</th>
                    <th>Сумма</th>
                    <th>Добавить</th>
                    <th>Удалить</th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    <tr>
                        <td>{{ item.product.title }}</td>
                        <td>{{ item.quantity }} шт.</td>
                        <td>{{ item.price }} руб.</td>
                        <td>{{ item.total_price }} руб.</td>
                        <td>
                            <form action="{% url 'cart:cart_add' item.product.pk 1 %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input type="submit" value="Добавить">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <a href="{% url 'cart:cart_remove' item.product.id %}">Удалить</a>
                        </td>
                    </tr>
                {% endfor %}
                <tr class="total">
                    <td colspan="3">Итого:</td>
                    <td>{{ cart.get_total_price }} руб.</td>
                </tr>
                </tbody>
            </table>
        {% else %}
            <div class="empty-cart">
                <p>Ваша корзина пуста</p>
            </div>
        {% endif %}
    {% endwith %}

    <div class="cart-actions">
        <a href="{% url 'book_list' %}" class="continue-shopping">Продолжить покупки</a>
        <a href="{% url 'order_detail' %}" class="checkout">Оформить заказ</a>
    </div>
{% endblock %}